"""Add_Media_Tables

Revision ID: ba9ae99e25e7
Revises: 5c9fb9b0587d
Create Date: 2026-02-13 09:06:33.247353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba9ae99e25e7'
down_revision: Union[str, None] = '5c9fb9b0587d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
